version:  '2.0'
services:
  cdbservice:
    container_name: cdbservice
    image: shuizhongmose/mpc-demo:cryptdb
    restart: unless-stopped
    ports:
      - "3306:3306"
      - "3399:3399"
    # volumes:
    #    - ./log/server:/cryptdb/log
    command:
      - /bin/bash
      - -c
      - |
        mysqld_safe &
        sleep 5
        source setup.sh
        mkdir shadow
        rm mysql-proxy.log -rf
        mysql-proxy --defaults-file=./mysql-proxy.cnf --proxy-lua-script=/cryptdb/wrapper.lua